---
- name: Create a directory for varnishncsa service configuration file
  ansible.builtin.file:
    path: /etc/systemd/system/varnishncsa.service.d
    state: directory
    mode: '0755'

- name: Copy varnishncsa log format file
  ansible.builtin.template:
    src: varnishncsa_log_format.j2
    dest: /var/log/varnish/varnishncsa_log_format
  notify: restart varnishncsa

- name: Copy varnishncsa service configuration file
  ansible.builtin.template:
    src: varnishncsa.service.j2
    dest: /etc/systemd/system/varnishncsa.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart varnishncsa
