---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set the packagecloud repository name based on the version.
  set_fact:
    varnish_packagecloud_repo: "varnish{{ varnish_version|replace('.', '') }}"

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: configure-varnish.yml

- include_tasks: configure-varnishncsa.yml
  when: varnish_ncsa_enabled | bool

- include_tasks: start-services.yml
  when: varnish_enabled_services | length > 0
